In [1]:
import pandas as pd
#the library is imported now lets import our data using a nice pandas function called read_csv
#we would do:
data = pd.read_csv('survey_results_public.csv')#
X = data.iloc[:,0:3]#variables
y = data.iloc[:,3]#variables

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [17]:
data.iloc[:5,:33]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0

In [9]:
data.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [25]:
df = data[['MainBranch', 'Hobbyist', 'OpenSourcer', 'Employment', 'Country', 'Student', 
           'EdLevel', 'UndergradMajor','CompFreq', 'ConvertedComp','Age', 'Gender']]

In [19]:
df.loc[df['CompFreq'] == 'Yearly']

In [26]:
df

,MainBranch,Hobbyist,OpenSourcer,Employment,Country,Student,EdLevel,UndergradMajor,CompFreq,ConvertedComp,Age,Gender
0,I am a student who is learning to code,Yes,Never,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,NaN,NaN,14.0,Man
1,I am a student who is learning to code,No,Less than once per year,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,NaN,NaN,19.0,Man
2,"I am not primarily a developer, but I write co...",Yes,Never,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Monthly,8820.0,28.0,Man
3,I am a developer by profession,No,Never,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Yearly,61000.0,22.0,Man
4,I am a developer by profession,Yes,Once a month or more often,Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,NaN,30.0,Man
5,"I am not primarily a developer, but I write co...",Yes,Never,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Monthly,366420.0,28.0,Man
6,I am a developer by profession,No,Never,"Independent contractor, freelancer, or self-em...",Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",NaN,NaN,42.0,Man
7,I code primarily as a hobby,Yes,Less than once per year,"Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,NaN,24.0,Man
8,I am a developer by profession,Yes,Once a month or more often,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Yearly,95179.0,23.0,Man
9,I am a developer by profession,Yes,Once a month or more often,Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Yearly,13293.0,NaN,NaN
10,I code primarily as a hobby,Yes,Once a month or more often,NaN,Antigua and Barbuda,"Yes, full-time",Primary/elementary school,NaN,NaN,NaN,22.0,Man
11,I am a student who is learning to code,No,Never,Employed part-time,Canada,"Yes, full-time",Some college/university study without earning ...,Mathematics or statistics,NaN,NaN,21.0,Woman
12,I am a developer by profession,Yes,Less than once a month but more than once per ...,Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Yearly,90000.0,28.0,Man
13,I am a developer by profession,Yes,Less than once per year,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",Monthly,57060.0,31.0,Man
14,I am a student who is learning to code,Yes,Never,"Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,NaN,NaN,20.0,Man
15,I am a developer by profession,Yes,Never,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Monthly,455352.0,26.0,Man
16,I am a developer by profession,Yes,Less than once a month but more than once per ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Yearly,65277.0,29.0,Man
17,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,Employed full-time,Russian Federation,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Monthly,21996.0,NaN,Man
18,I am a developer by profession,Yes,Never,Employed full-time,Brazil,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Monthly,31140.0,31.0,Man
19,"I am not primarily a developer, but I write co...",No,Never,Employed full-time,Lithuania,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",Monthly,41244.0,38.0,Man
20,I code primarily as a hobby,Yes,Once a month or more often,NaN,Canada,NaN,NaN,NaN,NaN,NaN,NaN,Man
21,I am a developer by profession,Yes,Less than once per year,Employed full-time,United States,No,Some college/university study without earning ...,NaN,Yearly,103000.0,47.0,Man
22,I am a developer by profession,Yes,Less than once per year,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Yearly,69000.0,22.0,Man
23,I am a developer by profession,Yes,Never,Employed full-time,Israel,No,Primary/elementary school,NaN,Monthly,26388.0,23.0,Man
24,I am a developer by profession,No,Never,Employed full-time,South Africa,No,Associate degree,"Computer science, computer engineering, or sof...",Monthly,6300.0,22.0,Man
25,I am a developer by profession,Yes,Less than once per year,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Yearly,114000.0,34.0,Man
26,"I used to be a developer by profession, but no...",Yes,Less than once per year,"Not employed, but looking for work",Colombia,"Yes, part-time",Some college/university study without earning ...,"Information systems, information technology, o...",NaN,NaN,22.0,Man
27,I am a developer by profession,Yes,Less than once per year,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Monthly,NaN,NaN,Man
28,I am a developer by profession,Yes,Less than once a month but more than once per ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Weekly,100000.0,32.0,Man
29,I am a developer by profession,No,Less than once a month but more than once per ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Yearly,90417.0,28.0,Man
...,...,...,...,...,...,...,...,...,...,...,...,...
88853,NaN,Yes,Never,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,NaN,NaN,NaN,NaN
88854,NaN,Yes,Less than once a month but more than once per ...,Employed full-time,United Kingdom,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,NaN,23.0,Woman
88855,NaN,No,Less than once a month but more than once per ...,NaN,Canada,NaN,NaN,NaN,NaN,NaN,NaN,Woman
88856,NaN,No,Never,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88857,NaN,No,Less than once a month but more than once per ...,"Independent contractor, freelancer, or self-em...",Sweden,No,"Professional degree (JD, MD, etc.)",NaN,NaN,NaN,NaN,Man
88858,NaN,No,Never,"Not employed, and not looking for work",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88859,NaN,No,Less than once per year,"Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",NaN,NaN,34.0,"Non-binary, genderqueer, or gender non-conforming"
88860,NaN,Yes,Never,"Not employed, and not looking for work",Brazil,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,NaN,NaN,15.0,Man
88861,NaN,No,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88862,NaN,Yes,Less than once per year,"Not employed, and not looking for work",Egypt,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Man
88863,NaN,Yes,Less than once per year,NaN,United Kingdom,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",NaN,NaN,45.0,Man
88864,NaN,Yes,Once a month or more often,Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...",NaN,NaN,24.0,Man
88865,NaN,Yes,Less than once a month but more than once per ...,Retired,Switzerland,No,Some college/university study without earning ...,"A humanities discipline (ex. literature, histo...",NaN,NaN,74.0,Man
88866,NaN,Yes,Never,"Not employed, and not looking for work",Australia,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",NaN,NaN,30.0,Man
88867,NaN,Yes,Once a month or more often,Employed part-time,Nigeria,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,NaN,NaN,19.0,Man
88868,NaN,No,Never,"Not employed, but looking for work",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88869,NaN,No,Never,"Not employed, and not looking for work",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88870,NaN,Yes,Less than once per year,"Not employed, and not looking for work",Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,NaN,59.0,Man
88871,NaN,Yes,Less than once a month but more than once per ...,"Independent contractor, freelancer, or self-em...",Italy,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,NaN,21.0,Man
88872,NaN,Yes,Less than once per year,Employed part-time,Czech Republic,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",NaN,NaN,25.0,NaN
88873,NaN,No,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88874,NaN,No,Never,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88875,NaN,Yes,Once a month or more often,Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Man
88876,NaN,No,Less than once per year,Employed full-time,Spain,No,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,40.0,Man
88877,NaN,Yes,Once a month or more often,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,Man
88878,NaN,Yes,Less than once a month but more than once per ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,NaN,NaN,NaN,Man
88879,NaN,No,Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,NaN,No,Never,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,NaN,No,Never,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,NaN,Yes,Less than once per year,"Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",NaN,NaN,18.0,Man

In [34]:
#import imputer
from sklearn.preprocessing import Imputer
#impute age
#we have to instantiate the imputer object with parameters that we need
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)#NaN means not a number. axis means which direction rows = 1, columns = 0
df.loc[:,['ConvertedComp','Age']] = imputer.fit_transform(df.loc[:,['ConvertedComp','Age']])

/home/kevin/.local/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [33]:
df.loc[:,['ConvertedComp','Age']]

       ConvertedComp        Age
0      127110.738423  14.000000
1      127110.738423  19.000000
2        8820.000000  28.000000
3       61000.000000  22.000000
4      127110.738423  30.000000
5      366420.000000  28.000000
6      127110.738423  42.000000
7      127110.738423  24.000000
8       95179.000000  23.000000
9       13293.000000  30.336699
10     127110.738423  22.000000
11     127110.738423  21.000000
12      90000.000000  28.000000
13      57060.000000  31.000000
14     127110.738423  20.000000
15     455352.000000  26.000000
16      65277.000000  29.000000
17      21996.000000  30.336699
18      31140.000000  31.000000
19      41244.000000  38.000000
20     127110.738423  30.336699
21     103000.000000  47.000000
22      69000.000000  22.000000
23      26388.000000  23.000000
24       6300.000000  22.000000
25     114000.000000  34.000000
26     127110.738423  22.000000
27     127110.738423  30.336699
28     100000.000000  32.000000
29      90417.000000  28.000000
...              ...        ...
88853  127110.738423  30.336699
88854  127110.738423  23.000000
88855  127110.738423  30.336699
88856  127110.738423  30.336699
88857  127110.738423  30.336699
88858  127110.738423  30.336699
88859  127110.738423  34.000000
88860  127110.738423  15.000000
88861  127110.738423  30.336699
88862  127110.738423  30.336699
88863  127110.738423  45.000000
88864  127110.738423  24.000000
88865  127110.738423  74.000000
88866  127110.738423  30.000000
88867  127110.738423  19.000000
88868  127110.738423  30.336699
88869  127110.738423  30.336699
88870  127110.738423  59.000000
88871  127110.738423  21.000000
88872  127110.738423  25.000000
88873  127110.738423  30.336699
88874  127110.738423  30.336699
88875  127110.738423  30.336699
88876  127110.738423  40.000000
88877  127110.738423  30.336699
88878  127110.738423  30.336699
88879  127110.738423  30.336699
88880  127110.738423  30.336699
88881  127110.738423  30.336699
88882  127110.738423  18.000000

[88883 rows x 2 columns]